#!/usr/bin/env bash
# display information about subdomains
domain_name=$1
if [ $# -eq 1 ]; then
    DNS_LIST="lb-01.$domain_name www.$domain_name web-01.$domain_name web-02.$domain_name"
    for subdomain in DNS_LIST; do
        record_type="$(dig $subdomain | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
        destination_ip="$(dig $subdomain | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
        echo "The subdomain $subdomain is a $record_type record and points to $destination_ip"
    done
else
    subdomain="$2.$domain_name"
    record_type="$(dig $subdomain | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    destination_ip="$(dig $subdomain | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $subdomain is a $record_type record and points to $destination_ip"
fi
